# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Display .NET info (debug step)
        run: dotnet --info

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test Horizons.Tests.Unit/Horizons.Tests.Unit.csproj --verbosity normal

      - name: Run Integration Tests
        run: dotnet test Horizons.Tests.Integration/Horizons.Tests.Integration.csproj --verbosity normal

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
